sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: java-gself
    region: cn-beijing
  redis:
    host: 192.168.83.100
    password: 123321
    port: 6379

  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 720000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: jj666
    user-token-name: token
    user-ttl: 720000000

  wechat:
    appid: wx17f36c65c5ec486d
    secret: 7b2735f34011f832929fcee99d7de7c3