sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: java-gself
    region: cn-beijing
  redis:
    host: 192.168.83.100
    password: 123321
    port: 6379
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: this_is_a_very_strong_secretKey_fuck_you_let_me_pass!!!
    # 设置jwt过期时间
    admin-ttl: 720000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: jj666_this_secretKey_is_too_short_i_have_to_enhance_it
    user-token-name: authentication
    user-ttl: 720000000

